FROM            sonarqube:alpine

RUN             wget -q -P /opt/sonarqube/extensions/plugins https://github.com/SonarOpenCommunity/sonar-cxx/releases/download/cxx-0.9.7/sonar-cxx-plugin-0.9.7.jar && \
                wget -q -P /opt/sonarqube/extensions/plugins https://github.com/uartois/sonar-golang/releases/download/v1.2.10/sonar-golang-plugin-1.2.10.jar

